### ISSUE TITLE
Command to generate config

### ISSUE THREAD

**Issue by frommie** [KMI-KPZ/rasahub#19]
Implement a command to create the configuration in current directory. There should be an option to list plugin names as parameters and get their needed init arguments.

Example:
python -m rasahub.config -p rasahub_humub -p rasahub_rasa -o config.yml 

Creates config.yml containing:

```
humhub:
  package: 'rasahub_humhub'
  init:
    host: '127.0.0.1'
    port: 3306
    dbname: 'humhub'
    dbuser: 'humhubuser'
    dbpasswd: 'dbpassword'
    trigger: '!bot'
  out: 'rasa'
  type: 'interface'

rasa:
  package: 'rasahub_rasa'
  init:
    host: '127.0.0.1'
    port: 5020
  out: 'humhub'
  type: 'interpreter'
```
